import { describe, expect, it } from "vitest";

import { validate } from "../schema/validate.js";
import { inferFrontmatter } from "./infer.js";

const TODAY = new Date("2026-08-31T00:00:00Z");

describe("inferFrontmatter", () => {
  it("derives a schema-valid id from the path and namespace", () => {
    const fm = inferFrontmatter({
      relPath: "architecture/01-overview.md",
      body: "# Overview\n\nText.\n",
      namespace: "architecture",
      gitAuthors: [],
      horizonDays: 180,
      today: TODAY,
    });
    expect(fm.id).toBe("architecture.architecture.01-overview");
    expect(validate("frontmatter", fm).ok).toBe(true);
  });

  it("takes the title from the first H1", () => {
    const fm = inferFrontmatter({
      relPath: "notes/billing-api.md",
      body: "intro line\n# Billing API Contract\nmore\n",
      namespace: "operating",
      gitAuthors: [],
      horizonDays: 180,
      today: TODAY,
    });
    expect(fm.title).toBe("Billing API Contract");
  });

  it("title-cases the filename stem when there is no H1", () => {
    const fm = inferFrontmatter({
      relPath: "operating/billing-api.md",
      body: "no heading here\n",
      namespace: "operating",
      gitAuthors: [],
      horizonDays: 180,
      today: TODAY,
    });
    expect(fm.title).toBe("Billing Api");
  });

  it("detects a synced source from a do-not-edit / edit-in header", () => {
    const fm = inferFrontmatter({
      relPath: "notes/b.md",
      body: "> Do not edit this file directly; edit in Notion and re-sync.\n\n# B\n",
      namespace: "operating",
      gitAuthors: [],
      horizonDays: 180,
      today: TODAY,
    });
    expect(fm.source).toBe("synced:notion");
  });

  it("prefers a named system over a generic '> Source:' line that appears first", () => {
    const fm = inferFrontmatter({
      relPath: "architecture/01-overview.md",
      body:
        "> Source: Project knowledge artifact 07-Technical-Architecture-v1.3\n" +
        "> Last synced: 2026-05-21\n" +
        "> Do not edit this file directly; edit in Notion and re-sync.\n\n# Overview\n",
      namespace: "operating",
      gitAuthors: [],
      horizonDays: 180,
      today: TODAY,
    });
    expect(fm.source).toBe("synced:notion");
  });

  it("picks the most frequent git author, breaking ties alphabetically", () => {
    const fm = inferFrontmatter({
      relPath: "operating/x.md",
      body: "# X\n",
      namespace: "operating",
      gitAuthors: ["Bob", "Ada", "Bob", "Ada", "Zoe"],
      horizonDays: 180,
      today: TODAY,
    });
    expect(fm.owner).toBe("Ada");
  });

  it("uses unassigned when there is no git history", () => {
    const fm = inferFrontmatter({
      relPath: "operating/x.md",
      body: "# X\n",
      namespace: "operating",
      gitAuthors: [],
      horizonDays: 180,
      today: TODAY,
    });
    expect(fm.owner).toBe("unassigned");
  });

  it("sets review_by to today plus the horizon in UTC when there is no git history", () => {
    const fm = inferFrontmatter({
      relPath: "operating/x.md",
      body: "# X\n",
      namespace: "operating",
      gitAuthors: [],
      horizonDays: 180,
      today: TODAY,
    });
    expect(fm.review_by).toBe("2027-02-27");
  });

  it("anchors review_by on the last git commit date, not on today, when known", () => {
    // Content last touched over two years before "today" — a fresh 180-day
    // grace period from today would hide that it is already badly overdue.
    const fm = inferFrontmatter({
      relPath: "operating/x.md",
      body: "# X\n",
      namespace: "operating",
      gitAuthors: [],
      horizonDays: 180,
      today: TODAY,
      lastModified: new Date("2024-01-10T00:00:00Z"),
    });
    expect(fm.review_by).toBe("2024-07-08");
    expect(fm.review_by < "2026-08-31").toBe(true); // already overdue as of TODAY
  });

  it("falls back to today when lastModified is explicitly null (no git history)", () => {
    const fm = inferFrontmatter({
      relPath: "operating/x.md",
      body: "# X\n",
      namespace: "operating",
      gitAuthors: [],
      horizonDays: 180,
      today: TODAY,
      lastModified: null,
    });
    expect(fm.review_by).toBe("2027-02-27");
  });

  it("parses a **Tags:** line into slugged tags", () => {
    const fm = inferFrontmatter({
      relPath: "operating/x.md",
      body: "# X\n\n**Tags:** Data Platform, Billing, ONBOARDING\n",
      namespace: "operating",
      gitAuthors: [],
      horizonDays: 180,
      today: TODAY,
    });
    expect(fm.tags).toEqual(["data-platform", "billing", "onboarding"]);
    expect(validate("frontmatter", fm).ok).toBe(true);
  });

  it("collapses a namespace containing a slash into a valid first id segment", () => {
    const fm = inferFrontmatter({
      relPath: "a/b.md",
      body: "# B\n",
      namespace: "team-ops/handbook",
      gitAuthors: [],
      horizonDays: 90,
      today: TODAY,
    });
    expect(fm.id).toBe("teamopshandbook.a.b");
    expect(validate("frontmatter", fm).ok).toBe(true);
  });
});
