// Deterministic. No model calls.
//
// `generateStub` emits a fill-in-the-blank catalog entry for a custom
// namespace / role / skill / persona that the toolkit does not ship. Every
// required field is present and every value carries a `# TODO:` — the stub
// never guesses content, it only lays out the shape the author must complete.

export type StubKind = "namespace" | "role" | "skill" | "persona";

const HEADER = "# STUB generated by team-ai — fill in every TODO before use.";

function todo(field: string, value: string, hint: string): string {
  return `${field}: ${value} # TODO: ${hint}`;
}

function seedDocStub(): string {
  return [
    `  - path: "" # TODO: path relative to kb/, inside a second_level dir`,
    `    title: "" # TODO: seed doc title`,
    `    purpose: "" # TODO: why this doc exists for the team`,
  ].join("\n");
}

function namespaceStub(name: string): string {
  return [
    HEADER,
    todo("name", `"${name}"`, "namespace key (kebab-case)"),
    todo("description", `""`, "one line on what this namespace holds"),
    todo("second_level", `[]`, "list the second-level directories (at least 1)"),
    todo("domain_dir", `null`, `"<prefix>/<name>" for a per-team dir, or null`),
    `seed_docs: # TODO: exactly 5 seed docs`,
    seedDocStub(),
    seedDocStub(),
    seedDocStub(),
    seedDocStub(),
    seedDocStub(),
    "",
  ].join("\n");
}

function roleStub(name: string): string {
  return [
    HEADER,
    todo("name", `"${name}"`, "role key (kebab-case)"),
    todo("summary", `""`, "one line on what this role owns"),
    todo("default_namespaces", `[]`, "namespace keys this role reads by default"),
    todo("default_skills", `[]`, "skill keys this role is granted by default"),
    todo("model_tier", `"none"`, "none | small | large"),
    todo("persona_default", `""`, "persona key for this role's register"),
    "",
  ].join("\n");
}

function skillStub(name: string): string {
  return [
    HEADER,
    todo("name", `"${name}"`, "skill key (kebab-case)"),
    todo("tier", `"none"`, "none | small | large"),
    todo("summary", `""`, "one line on what this skill does"),
    todo("presets", `[]`, `"all" or a list of preset keys`),
    "",
  ].join("\n");
}

function personaStub(name: string): string {
  return [
    "---",
    `name: ${name}`,
    "kind: persona",
    "grants: none",
    "---",
    "",
    HEADER,
    "",
    "TODO: one paragraph on tone and register — how this voice sounds.",
    "",
    "TODO: one paragraph on what this voice avoids and where it fits.",
    "",
  ].join("\n");
}

export function generateStub(name: string, kind: StubKind): string {
  switch (kind) {
    case "namespace":
      return namespaceStub(name);
    case "role":
      return roleStub(name);
    case "skill":
      return skillStub(name);
    case "persona":
      return personaStub(name);
  }
}
