import { describe, expect, it } from "vitest";

import { parse as parseYaml } from "yaml";

import { generateStub } from "./stub.js";

const HEADER = "# STUB generated by team-ai";

function fieldLines(text: string): string[] {
  return text
    .split("\n")
    .filter((line) => /^[a-z_]+:/.test(line.trimStart()) && !line.startsWith("#"));
}

describe("generateStub", () => {
  it("emits every role field with a TODO on each", () => {
    const stub = generateStub("x", "role");
    expect(stub).toContain(HEADER);
    const required = [
      "name",
      "summary",
      "default_namespaces",
      "default_skills",
      "model_tier",
      "persona_default",
    ];
    for (const field of required) {
      const line = stub.split("\n").find((l) => l.startsWith(`${field}:`));
      expect(line, `field ${field}`).toBeDefined();
      expect(line).toContain("# TODO:");
    }
  });

  it("emits every namespace field with a TODO on each", () => {
    const stub = generateStub("y", "namespace");
    expect(stub).toContain(HEADER);
    for (const field of ["name", "description", "second_level", "domain_dir", "seed_docs"]) {
      const line = stub.split("\n").find((l) => l.startsWith(`${field}:`));
      expect(line, `field ${field}`).toBeDefined();
      expect(line).toContain("# TODO:");
    }
    // Every top-level field line carries a TODO marker.
    for (const line of fieldLines(stub)) expect(line).toContain("# TODO");
  });

  it("produces a persona stub as markdown front matter with kind: persona", () => {
    const stub = generateStub("z", "persona");
    expect(stub.startsWith("---\n")).toBe(true);
    expect(stub).toContain("kind: persona");
    expect(stub).toContain("grants: none");
    expect(stub).toContain("TODO");
  });

  it("never guesses: the skill stub still parses as YAML with placeholder values", () => {
    const parsed = parseYaml(generateStub("q", "skill")) as Record<string, unknown>;
    expect(Object.keys(parsed).sort()).toEqual(["name", "presets", "summary", "tier"]);
  });
});
