import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, it, vi } from "vitest";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";

import { run } from "../commands/assemble-manifest.js";
import { validate } from "../schema/validate.js";
import type { ManifestDomain } from "../schema/types.js";
import { assembleManifest, serializeManifest } from "./assemble.js";

function manifestDomain(over: Partial<ManifestDomain> & { id: string }): ManifestDomain {
  return {
    description: `${over.id} domain`,
    keywords: [over.id],
    kb_namespace: `ns-${over.id}`,
    subagent: `${over.id}-agent`,
    model_tier: "small",
    owner: "@owner",
    ...over,
  };
}

function spokeConfig(over: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    name: "payments",
    kb_namespace: "payments",
    owner: "@payments-lead",
    core_repo: "org/payments",
    toolkit_version: "0.1.0",
    domains: [
      {
        id: "refunds",
        description: "Refund handling",
        keywords: ["refund"],
        subagent: "refunds-agent",
        model_tier: "large",
      },
    ],
    ...over,
  };
}

describe("assembleManifest", () => {
  it("returns fragment domains sorted by id", () => {
    const fragment = { domains: [manifestDomain({ id: "beta" }), manifestDomain({ id: "alpha" })] };
    const result = assembleManifest({ fragment, spokes: [] });

    expect(result.domains.map((d) => d.id)).toEqual(["alpha", "beta"]);
    expect(validate("manifest", result).ok).toBe(true);
  });

  it("promotes spoke domains with kb_namespace, owner, and repo from the spoke config", () => {
    const fragment = { domains: [manifestDomain({ id: "hub-a" })] };
    const result = assembleManifest({
      fragment,
      spokes: [{ name: "payments", config: spokeConfig() }],
    });

    expect(result.domains.map((d) => d.id)).toEqual(["hub-a", "refunds"]);
    const refunds = result.domains.find((d) => d.id === "refunds");
    expect(refunds).toMatchObject({
      kb_namespace: "payments",
      owner: "@payments-lead",
      repo: "org/payments",
      subagent: "refunds-agent",
      model_tier: "large",
    });
    expect(validate("manifest", result).ok).toBe(true);
  });

  it("throws when a domain id collides across sources, naming both", () => {
    const fragment = { domains: [manifestDomain({ id: "x" })] };
    const config = spokeConfig({
      name: "s",
      domains: [
        {
          id: "x",
          description: "d",
          keywords: ["k"],
          subagent: "a",
          model_tier: "small",
        },
      ],
    });

    expect(() => assembleManifest({ fragment, spokes: [{ name: "s", config }] })).toThrow(
      /duplicate domain id 'x' \(from instance and spoke:s\)/,
    );
  });

  it("throws 'spoke '<name>'' when a spoke config is invalid", () => {
    expect(() =>
      assembleManifest({
        fragment: undefined,
        spokes: [{ name: "broken", config: { name: "broken" } }],
      }),
    ).toThrow(/^spoke 'broken':/);
  });

  it("returns an empty manifest for an empty fragment and no spokes", () => {
    const result = assembleManifest({ fragment: undefined, spokes: [] });

    expect(result).toEqual({ domains: [] });
    expect(validate("manifest", result).ok).toBe(true);
  });
});

describe("serializeManifest", () => {
  it("round-trips through yaml.parse", () => {
    const manifest = assembleManifest({
      fragment: {
        domains: [
          manifestDomain({ id: "b", repo: "org/b", escalate_to: "@esc" }),
          manifestDomain({ id: "a" }),
        ],
      },
      spokes: [],
    });

    const parsed: unknown = parseYaml(serializeManifest(manifest));
    expect(parsed).toEqual(manifest);
  });

  it("emits the do-not-edit header and a stable key order per domain", () => {
    const text = serializeManifest(
      assembleManifest({
        fragment: { domains: [manifestDomain({ id: "a", repo: "org/r", escalate_to: "@e" })] },
        spokes: [],
      }),
    );

    expect(text.startsWith("# Generated by team-ai assemble-manifest.")).toBe(true);
    const keys = [...text.matchAll(/^ *(?:- )?(\w+):/gm)]
      .map((m) => m[1])
      .filter((k) => k !== "domains");
    expect(keys.slice(0, 9)).toEqual([
      "id",
      "description",
      "keywords",
      "kb_namespace",
      "subagent",
      "model_tier",
      "owner",
      "repo",
      "escalate_to",
    ]);
  });
});

const log = vi.spyOn(console, "log").mockImplementation(() => undefined);
const error = vi.spyOn(console, "error").mockImplementation(() => undefined);
const dirs: string[] = [];

function scaffold(): string {
  const root = mkdtempSync(join(tmpdir(), "team-ai-assemble-"));
  dirs.push(root);
  mkdirSync(join(root, "agents"), { recursive: true });
  writeFileSync(
    join(root, "agents", "manifest.fragment.yaml"),
    stringifyYaml({
      domains: [
        {
          id: "ops",
          description: "Ops",
          keywords: ["ops"],
          kb_namespace: "operating",
          subagent: "ops-agent",
          model_tier: "small",
          owner: "@ops",
        },
      ],
    }),
    "utf8",
  );
  return root;
}

afterEach(() => {
  log.mockClear();
  error.mockClear();
  for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true });
});

describe("assemble-manifest command", () => {
  it("writes manifest.yaml then reports up to date under --check", async () => {
    const root = scaffold();

    expect(await run({ root, check: false })).toBe(0);
    const written = readFileSync(join(root, "manifest.yaml"), "utf8");
    expect(written).toContain("# Generated by team-ai assemble-manifest.");
    expect(log.mock.calls.map((c) => String(c[0])).join("\n")).toMatch(
      /wrote manifest\.yaml \(1 domains\)/,
    );

    log.mockClear();
    expect(await run({ root, check: true })).toBe(0);
    expect(log.mock.calls.map((c) => String(c[0])).join("\n")).toMatch(/up to date \(1 domains\)/);
  });

  it("flags a stale manifest.yaml under --check after the fragment changes", async () => {
    const root = scaffold();
    await run({ root, check: false });

    writeFileSync(
      join(root, "agents", "manifest.fragment.yaml"),
      stringifyYaml({
        domains: [
          {
            id: "ops",
            description: "Ops",
            keywords: ["ops"],
            kb_namespace: "operating",
            subagent: "ops-agent",
            model_tier: "small",
            owner: "@ops",
          },
          {
            id: "sec",
            description: "Security",
            keywords: ["sec"],
            kb_namespace: "security",
            subagent: "sec-agent",
            model_tier: "small",
            owner: "@sec",
          },
        ],
      }),
      "utf8",
    );

    expect(await run({ root, check: true })).toBe(1);
    const err = error.mock.calls.map((c) => String(c[0])).join("\n");
    expect(err).toMatch(/stale/);
    expect(err).toMatch(/sec/);
  });

  it("returns 1 when --check runs with no manifest.yaml", async () => {
    const root = scaffold();
    expect(await run({ root, check: true })).toBe(1);
    expect(error.mock.calls.map((c) => String(c[0])).join("\n")).toMatch(/manifest\.yaml missing/);
  });

  it("merges spoke.yaml files found under spokes/", async () => {
    const root = scaffold();
    mkdirSync(join(root, "spokes", "payments"), { recursive: true });
    writeFileSync(
      join(root, "spokes", "payments", "spoke.yaml"),
      stringifyYaml(spokeConfig()),
      "utf8",
    );

    expect(await run({ root, check: false })).toBe(0);
    const written = readFileSync(join(root, "manifest.yaml"), "utf8");
    expect(written).toContain("id: refunds");
    expect(written).toContain("repo: org/payments");
    expect(log.mock.calls.map((c) => String(c[0])).join("\n")).toMatch(
      /wrote manifest\.yaml \(2 domains\)/,
    );
  });
});
