// Deterministic. No model calls.
//
// Pure merge logic behind the `assemble-manifest` command. Combines the instance
// manifest fragment (agents/manifest.fragment.yaml) with any spoke spoke.yaml
// files into one schema-valid manifest. All file IO lives in the CLI wrapper at
// src/commands/assemble-manifest.ts.

import { stringify as stringifyYaml } from "yaml";

import type { Manifest, ManifestAgent, ManifestDomain, ManifestSkill } from "../schema/types.js";
import { validate } from "../schema/validate.js";

export interface AssembleInput {
  fragment: unknown;
  spokes: { name: string; config: unknown }[];
}

const MANIFEST_HEADER =
  "# Generated by team-ai assemble-manifest. Do not edit by hand — edit agents/manifest.fragment.yaml or a spoke.";

const DOMAIN_KEY_ORDER: readonly (keyof ManifestDomain)[] = [
  "id",
  "description",
  "keywords",
  "kb_namespace",
  "subagent",
  "model_tier",
  "owner",
  "repo",
  "escalate_to",
  "group",
  "authority",
  "not_owned",
  "depends_on",
];

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function firstError(errors: string[]): string {
  return errors[0] ?? "validation failed";
}

function stringOr(value: unknown, fallback: string): string {
  return typeof value === "string" && value.length > 0 ? value : fallback;
}

function readAgents(fragment: unknown): ManifestAgent[] | undefined {
  if (!isRecord(fragment) || !Array.isArray(fragment.agents)) return undefined;
  return [...(fragment.agents as ManifestAgent[])];
}

function readSkills(fragment: unknown): ManifestSkill[] | undefined {
  if (!isRecord(fragment) || !Array.isArray(fragment.skills)) return undefined;
  return [...(fragment.skills as ManifestSkill[])];
}

// The fragment is expected to already hold full ManifestDomain objects, so the
// cheapest validation is to run the whole `{ domains }` through the manifest
// schema.
function resolveFragmentDomains(fragment: unknown): ManifestDomain[] {
  if (fragment === undefined || fragment === null) return [];
  if (!isRecord(fragment)) {
    throw new Error("instance manifest fragment: expected a mapping with a 'domains' array");
  }
  const domains = fragment.domains;
  if (domains === undefined || domains === null) return [];
  if (!Array.isArray(domains)) {
    throw new Error("instance manifest fragment: 'domains' must be an array");
  }
  if (domains.length === 0) return [];

  const result = validate("manifest", { domains });
  if (!result.ok) {
    throw new Error(`instance manifest fragment: ${firstError(result.errors)}`);
  }
  return result.value.domains;
}

function promoteSpokeDomains(spoke: { name: string; config: unknown }): ManifestDomain[] {
  const result = validate("spoke", spoke.config);
  if (!result.ok) {
    throw new Error(`spoke '${spoke.name}': ${firstError(result.errors)}`);
  }
  const config = result.value;

  return config.domains.map((domain) => {
    const raw = domain as unknown as Record<string, unknown>;
    const promoted: ManifestDomain = {
      id: domain.id,
      description: domain.description,
      keywords: [...domain.keywords],
      kb_namespace: stringOr(raw.kb_namespace, config.kb_namespace),
      subagent: domain.subagent,
      model_tier: domain.model_tier,
      owner: stringOr(raw.owner, config.owner),
      repo: stringOr(raw.repo, config.core_repo),
    };
    if (domain.escalate_to !== undefined) {
      promoted.escalate_to = domain.escalate_to;
    }
    return promoted;
  });
}

export function assembleManifest(input: AssembleInput): Manifest {
  const source = new Map<string, string>();
  const collected: ManifestDomain[] = [];

  const register = (domain: ManifestDomain, from: string): void => {
    const existing = source.get(domain.id);
    if (existing !== undefined) {
      throw new Error(`duplicate domain id '${domain.id}' (from ${existing} and ${from})`);
    }
    source.set(domain.id, from);
    collected.push(domain);
  };

  for (const domain of resolveFragmentDomains(input.fragment)) {
    register(domain, "instance");
  }
  for (const spoke of input.spokes) {
    for (const domain of promoteSpokeDomains(spoke)) {
      register(domain, `spoke:${spoke.name}`);
    }
  }

  const domains = collected.sort((a, b) => a.id.localeCompare(b.id));
  const assembled: Manifest = { domains };
  const agents = readAgents(input.fragment);
  if (agents !== undefined) assembled.agents = agents;
  const skills = readSkills(input.fragment);
  if (skills !== undefined) assembled.skills = skills;

  const guard = validate("manifest", assembled);
  if (!guard.ok) {
    throw new Error(`assembled manifest is invalid: ${firstError(guard.errors)}`);
  }
  if (assembled.agents !== undefined) {
    assembled.agents.sort((a, b) => a.name.localeCompare(b.name));
  }
  if (assembled.skills !== undefined) {
    assembled.skills.sort((a, b) => a.id.localeCompare(b.id));
  }
  return guard.value;
}

function orderDomainKeys(domain: ManifestDomain): Record<string, unknown> {
  const ordered: Record<string, unknown> = {};
  for (const key of DOMAIN_KEY_ORDER) {
    const value = domain[key];
    if (value !== undefined) ordered[key] = value;
  }
  return ordered;
}

export function serializeManifest(manifest: Manifest): string {
  const domains = [...manifest.domains]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((domain) => orderDomainKeys(domain));
  const out: Record<string, unknown> = { domains };
  if (manifest.agents !== undefined) {
    out.agents = [...manifest.agents].sort((a, b) => a.name.localeCompare(b.name));
  }
  if (manifest.skills !== undefined) {
    out.skills = [...manifest.skills].sort((a, b) => a.id.localeCompare(b.id));
  }
  return `${MANIFEST_HEADER}\n${stringifyYaml(out)}`;
}
