import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import {
  DEFAULT_INDEX_LOCK,
  lockChanged,
  readIndexLock,
  resolveKbScope,
  writeIndexLock,
  type IndexLock,
} from "./index-lock.js";

const dirs: string[] = [];

function tempDir(): string {
  const dir = mkdtempSync(join(tmpdir(), "tai-"));
  dirs.push(dir);
  return dir;
}

function clone(lock: IndexLock): IndexLock {
  return JSON.parse(JSON.stringify(lock)) as IndexLock;
}

afterEach(() => {
  while (dirs.length > 0) {
    const dir = dirs.pop();
    if (dir) rmSync(dir, { recursive: true, force: true });
  }
});

describe("readIndexLock", () => {
  it("returns a deep copy of the default when no index.lock exists", () => {
    const dir = tempDir();
    expect(readIndexLock(dir)).toEqual(DEFAULT_INDEX_LOCK);
  });

  it("returns a fresh copy each call — mutation does not leak into the default", () => {
    const dir = tempDir();
    const a = readIndexLock(dir);
    a.driver = "vector-embedded";
    a.chunk.split_on.push("h4");
    a.chunk.target_tokens = 1;
    const b = readIndexLock(dir);
    expect(b).toEqual(DEFAULT_INDEX_LOCK);
    expect(DEFAULT_INDEX_LOCK.driver).toBe("lexical");
    expect(DEFAULT_INDEX_LOCK.chunk.split_on).toEqual(["h2", "h3"]);
    expect(DEFAULT_INDEX_LOCK.chunk.target_tokens).toBe(800);
  });

  it("round-trips through writeIndexLock", () => {
    const dir = tempDir();
    const lock: IndexLock = {
      driver: "vector-embedded",
      chunk: { split_on: ["h2"], target_tokens: 600, hard_cap: 1000 },
      embedding: { provider: "openai", model: "text-embedding-3-small", version: "1" },
    };
    writeIndexLock(dir, lock);
    expect(readIndexLock(dir)).toEqual(lock);
  });

  it("round-trips a null embedding", () => {
    const dir = tempDir();
    writeIndexLock(dir, DEFAULT_INDEX_LOCK);
    expect(readIndexLock(dir)).toEqual(DEFAULT_INDEX_LOCK);
  });

  it("writes the generated-by comment", () => {
    const dir = tempDir();
    writeIndexLock(dir, DEFAULT_INDEX_LOCK);
    const raw = readFileSync(join(dir, "index.lock"), "utf8");
    expect(raw.startsWith("# Generated by team-ai.")).toBe(true);
  });

  it("throws on a negative target_tokens", () => {
    const dir = tempDir();
    writeFileSync(
      join(dir, "index.lock"),
      "driver: lexical\nchunk:\n  split_on: [h2]\n  target_tokens: -5\n  hard_cap: 1200\nembedding: null\n",
    );
    expect(() => readIndexLock(dir)).toThrow(/invalid index\.lock/);
  });

  it("throws when hard_cap is below target_tokens", () => {
    const dir = tempDir();
    writeFileSync(
      join(dir, "index.lock"),
      "driver: lexical\nchunk:\n  split_on: [h2]\n  target_tokens: 900\n  hard_cap: 800\nembedding: null\n",
    );
    expect(() => readIndexLock(dir)).toThrow(/invalid index\.lock/);
  });

  it("throws when chunk is missing", () => {
    const dir = tempDir();
    writeFileSync(join(dir, "index.lock"), "driver: lexical\nembedding: null\n");
    expect(() => readIndexLock(dir)).toThrow(/invalid index\.lock/);
  });

  it("throws on an empty driver", () => {
    const dir = tempDir();
    writeFileSync(
      join(dir, "index.lock"),
      "driver: ''\nchunk:\n  split_on: [h2]\n  target_tokens: 800\n  hard_cap: 1200\nembedding: null\n",
    );
    expect(() => readIndexLock(dir)).toThrow(/invalid index\.lock/);
  });

  it("throws on an embedding object with a blank field", () => {
    const dir = tempDir();
    writeFileSync(
      join(dir, "index.lock"),
      "driver: vector-embedded\nchunk:\n  split_on: [h2]\n  target_tokens: 800\n  hard_cap: 1200\nembedding:\n  provider: openai\n  model: ''\n  version: '1'\n",
    );
    expect(() => readIndexLock(dir)).toThrow(/invalid index\.lock/);
  });

  it("throws on non-string split_on entries", () => {
    const dir = tempDir();
    writeFileSync(
      join(dir, "index.lock"),
      "driver: lexical\nchunk:\n  split_on: [2, 3]\n  target_tokens: 800\n  hard_cap: 1200\nembedding: null\n",
    );
    expect(() => readIndexLock(dir)).toThrow(/invalid index\.lock/);
  });

  it("throws on a non-integer target_tokens", () => {
    const dir = tempDir();
    writeFileSync(
      join(dir, "index.lock"),
      "driver: lexical\nchunk:\n  split_on: [h2]\n  target_tokens: 800.5\n  hard_cap: 1200\nembedding: null\n",
    );
    expect(() => readIndexLock(dir)).toThrow(/invalid index\.lock/);
  });
});

describe("lockChanged", () => {
  const base: IndexLock = {
    driver: "lexical",
    chunk: { split_on: ["h2", "h3"], target_tokens: 800, hard_cap: 1200 },
    embedding: null,
  };

  it("is false for identical locks", () => {
    expect(lockChanged(base, clone(base))).toBe(false);
  });

  it("is true when the driver changes", () => {
    const b = clone(base);
    b.driver = "vector-embedded";
    expect(lockChanged(base, b)).toBe(true);
  });

  it("is true when target_tokens changes", () => {
    const b = clone(base);
    b.chunk.target_tokens = 900;
    expect(lockChanged(base, b)).toBe(true);
  });

  it("is true when split_on changes", () => {
    const b = clone(base);
    b.chunk.split_on = ["h2"];
    expect(lockChanged(base, b)).toBe(true);
  });

  it("is true when split_on order changes", () => {
    const b = clone(base);
    b.chunk.split_on = ["h3", "h2"];
    expect(lockChanged(base, b)).toBe(true);
  });

  it("is true when embedding goes from null to an object", () => {
    const b = clone(base);
    b.embedding = { provider: "openai", model: "text-embedding-3-small", version: "1" };
    expect(lockChanged(base, b)).toBe(true);
  });

  it("is false for two equal embedding objects", () => {
    const a: IndexLock = {
      ...clone(base),
      embedding: { provider: "openai", model: "m", version: "1" },
    };
    const b: IndexLock = {
      ...clone(base),
      embedding: { provider: "openai", model: "m", version: "1" },
    };
    expect(lockChanged(a, b)).toBe(false);
  });

  it("is true when an embedding field differs", () => {
    const a: IndexLock = {
      ...clone(base),
      embedding: { provider: "openai", model: "m", version: "1" },
    };
    const b: IndexLock = {
      ...clone(base),
      embedding: { provider: "openai", model: "m", version: "2" },
    };
    expect(lockChanged(a, b)).toBe(true);
  });

  it("is true when the KB root changes", () => {
    const a: IndexLock = { ...clone(base), kb: { root: "kb", exclude: [] } };
    const b: IndexLock = { ...clone(base), kb: { root: "docs", exclude: [] } };
    expect(lockChanged(a, b)).toBe(true);
  });

  it("is true when KB exclusions change", () => {
    const a: IndexLock = { ...clone(base), kb: { root: "docs", exclude: ["archive/"] } };
    const b: IndexLock = { ...clone(base), kb: { root: "docs", exclude: ["drafts/"] } };
    expect(lockChanged(a, b)).toBe(true);
  });

  it("is false for equal KB scopes", () => {
    const a: IndexLock = { ...clone(base), kb: { root: "docs", exclude: ["archive/"] } };
    expect(lockChanged(a, clone(a))).toBe(false);
  });
});

describe("index.lock kb scope", () => {
  it("resolves the declared KB root and exclusions against the instance directory", () => {
    const dir = mkdtempSync(join(tmpdir(), "team-ai-lock-"));
    writeFileSync(
      join(dir, "index.lock"),
      "driver: lexical\nchunk:\n  split_on: [h2, h3]\n  target_tokens: 800\n  hard_cap: 1200\nembedding: null\nkb:\n  root: ../docs\n  exclude: [archive/]\n",
      "utf8",
    );
    const scope = resolveKbScope(dir);
    expect(scope.root).toBe(resolve(dir, "..", "docs"));
    expect(scope.exclude).toEqual(["archive/"]);
    rmSync(dir, { recursive: true, force: true });
  });

  it("defaults to <instance>/kb with no exclusions when the lock has no kb block", () => {
    const dir = mkdtempSync(join(tmpdir(), "team-ai-lock-"));
    writeIndexLock(dir, DEFAULT_INDEX_LOCK);
    expect(resolveKbScope(dir)).toEqual({ root: join(dir, "kb"), exclude: [] });
    rmSync(dir, { recursive: true, force: true });
  });
});
