import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { parse as parseYaml, stringify as stringifyYaml } from "yaml";

export interface IndexLockEmbedding {
  provider: string;
  model: string;
  version: string;
}

export interface IndexLockKb {
  root: string;
  exclude: string[];
}

export interface IndexLock {
  driver: string;
  chunk: {
    split_on: string[];
    target_tokens: number;
    hard_cap: number;
  };
  embedding: IndexLockEmbedding | null;
  kb?: IndexLockKb;
}

export const DEFAULT_INDEX_LOCK: IndexLock = {
  driver: "lexical",
  chunk: { split_on: ["h2", "h3"], target_tokens: 800, hard_cap: 1200 },
  embedding: null,
};

const LOCK_FILE = "index.lock";
const HEADER = "# Generated by team-ai. Changing any value forces a full reindex.";

function cloneLock(lock: IndexLock): IndexLock {
  return {
    driver: lock.driver,
    chunk: {
      split_on: [...lock.chunk.split_on],
      target_tokens: lock.chunk.target_tokens,
      hard_cap: lock.chunk.hard_cap,
    },
    embedding: lock.embedding === null ? null : { ...lock.embedding },
    ...(lock.kb ? { kb: { root: lock.kb.root, exclude: [...lock.kb.exclude] } } : {}),
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0;
}

function isPositiveInt(value: unknown): value is number {
  return typeof value === "number" && Number.isInteger(value) && value > 0;
}

function parseEmbedding(value: unknown): IndexLockEmbedding | null {
  if (value === null) return null;
  if (!isRecord(value)) throw new Error("embedding must be null or an object");
  const { provider, model, version } = value;
  if (!isNonEmptyString(provider) || !isNonEmptyString(model) || !isNonEmptyString(version)) {
    throw new Error("embedding must have non-empty provider, model, and version strings");
  }
  return { provider, model, version };
}

function parseLock(value: unknown): IndexLock {
  if (!isRecord(value)) throw new Error("expected a mapping");

  const { driver, chunk, embedding } = value;
  if (!isNonEmptyString(driver)) throw new Error("driver must be a non-empty string");
  if (!("embedding" in value)) throw new Error("embedding is required (null or an object)");

  if (!isRecord(chunk)) throw new Error("chunk must be an object");
  const { split_on, target_tokens, hard_cap } = chunk;

  if (
    !Array.isArray(split_on) ||
    split_on.length === 0 ||
    !split_on.every((entry): entry is string => typeof entry === "string")
  ) {
    throw new Error("chunk.split_on must be a non-empty array of strings");
  }
  if (!isPositiveInt(target_tokens)) {
    throw new Error("chunk.target_tokens must be a positive integer");
  }
  if (!isPositiveInt(hard_cap)) {
    throw new Error("chunk.hard_cap must be a positive integer");
  }
  if (hard_cap < target_tokens) {
    throw new Error("chunk.hard_cap must be >= chunk.target_tokens");
  }

  const lock: IndexLock = {
    driver,
    chunk: { split_on: [...split_on], target_tokens, hard_cap },
    embedding: parseEmbedding(embedding),
  };

  if ("kb" in value && value.kb !== undefined) {
    const kb = value.kb;
    if (!isRecord(kb) || !isNonEmptyString(kb.root)) {
      throw new Error("kb must be an object with a non-empty root");
    }
    const exclude = kb.exclude ?? [];
    if (!Array.isArray(exclude) || !exclude.every((e) => isNonEmptyString(e))) {
      throw new Error("kb.exclude must be a list of non-empty strings");
    }
    lock.kb = { root: kb.root, exclude: [...exclude] };
  }

  return lock;
}

export function readIndexLock(dir: string): IndexLock {
  const path = join(dir, LOCK_FILE);

  let raw: string;
  try {
    raw = readFileSync(path, "utf8");
  } catch (err) {
    if (err instanceof Error && "code" in err && err.code === "ENOENT") {
      return cloneLock(DEFAULT_INDEX_LOCK);
    }
    throw err;
  }

  let parsed: unknown;
  try {
    parsed = parseYaml(raw);
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);
    throw new Error(`invalid index.lock at ${path}: ${reason}`);
  }

  try {
    return parseLock(parsed);
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);
    throw new Error(`invalid index.lock at ${path}: ${reason}`);
  }
}

export function writeIndexLock(dir: string, lock: IndexLock): void {
  const ordered = {
    driver: lock.driver,
    chunk: {
      split_on: [...lock.chunk.split_on],
      target_tokens: lock.chunk.target_tokens,
      hard_cap: lock.chunk.hard_cap,
    },
    embedding:
      lock.embedding === null
        ? null
        : {
            provider: lock.embedding.provider,
            model: lock.embedding.model,
            version: lock.embedding.version,
          },
    ...(lock.kb ? { kb: { root: lock.kb.root, exclude: [...lock.kb.exclude] } } : {}),
  };
  const body = stringifyYaml(ordered);
  writeFileSync(join(dir, LOCK_FILE), `${HEADER}\n${body}`, "utf8");
}

export function resolveKbScope(instanceDir: string): { root: string; exclude: string[] } {
  const lock = readIndexLock(instanceDir);
  if (lock.kb === undefined) return { root: join(instanceDir, "kb"), exclude: [] };
  return { root: resolve(instanceDir, lock.kb.root), exclude: [...lock.kb.exclude] };
}

export function lockChanged(a: IndexLock, b: IndexLock): boolean {
  if (a.driver !== b.driver) return true;

  if (a.chunk.target_tokens !== b.chunk.target_tokens) return true;
  if (a.chunk.hard_cap !== b.chunk.hard_cap) return true;
  if (a.chunk.split_on.length !== b.chunk.split_on.length) return true;
  if (a.chunk.split_on.some((entry, i) => entry !== b.chunk.split_on[i])) return true;

  if (a.embedding === null || b.embedding === null) {
    return a.embedding !== b.embedding;
  }
  return (
    a.embedding.provider !== b.embedding.provider ||
    a.embedding.model !== b.embedding.model ||
    a.embedding.version !== b.embedding.version
  );
}
